CREATE TABLE `USER` (
   `USER_SEQUENCE`   INT   NOT NULL AUTO_INCREMENT PRIMARY KEY,
   `USER_ID`   VARCHAR(20)   NULL,
   `USER_PASSWORD`   VARCHAR(30)   NULL,
   `USER_NAME`   VARCHAR(30)   NULL,
   `USER_PHONENUM`   VARCHAR(30)   NULL,
   `USER_CARNUM`   VARCHAR(30)   NULL,
   `USER_CARTYPE`   VARCHAR(30)   NULL,
   `USER_CARNUMCOLOR`   VARCHAR(30)   NULL,
   `USER_BANKNAME`   VARCHAR(30)   NULL,
   `USER_ACCOUNT`   VARCHAR(30)   NULL,
   `USER_COURYAREA`   VARCHAR(100)   NULL
);

CREATE TABLE `COURY` (
   `COURY_SEQUENCE`   INT   NOT NULL AUTO_INCREMENT PRIMARY KEY,
   `USER_SEQUENCE`   INT(20)   NULL,
   `COURY_METHOD`   VARCHAR(20)   NULL,
   `COURY_ASSIGNMENT`   VARCHAR(1)   NULL,
   `COURY_CONDITION`   VARCHAR(10)   NULL,
   `COURY_PICTURENAME`   VARCHAR(50)   NULL,
   `COURY_PICTUREWAY`   VARCHAR(100)   NULL,
   `COURY_WAYBILL`   INT(12)    NULL,
   `COURY_FROM_ADDRESS`   VARCHAR(100)   NULL,
   `COURY_TO_ADDRESS`   VARCHAR(100)   NULL,
   `COURY_FROM_NAME`   VARCHAR(100)   NULL,
   `COURY_TO_NAME`   VARCHAR(100)   NULL,
   `COURY_FROM_PHONENUM`   VARCHAR(20)   NULL,
   `COURY_TO_PHONENUM`   VARCHAR(20)   NULL,
   `COURY_GETPLACE`   VARCHAR(10)   NULL,
   `COURY_SIGNIFICANT`   VARCHAR(200)   NULL,
   `COURY_BARCODE`   VARCHAR(30)   NULL,
   `EXPRESS_DATE`   VARCHAR(20)   NULL,
   `EXPRESS_TIME`   VARCHAR(20)   NULL,
   `EXPRESS_NUM`   VARCHAR(20)     NULL,
   `AREA`   VARCHAR(100)    NULL,
   `CATEGORY`    VARCHAR(50)   NULL,
   `ADDR_TYPE`   VARCHAR(20)   NULL,
   `WEIGHT`   VARCHAR(20)    NULL,
   `SIZE`   VARCHAR(20)    NULL,
   `EXPRESS_STATE`   VARCHAR(20)   NULL,
   `PACKAGE_NAME`   VARCHAR(20)   NULL,
);

CREATE TABLE `PICKUP` (
   `PICKUP_SEQUENCE`   INT   NOT NULL AUTO_INCREMENT PRIMARY KEY,
   `USER_SEQUENCE`   VARCHAR(20)   NULL,
   `PICKUP_YN`   CHAR(1)   NULL,
   `PICKUP-TIME`   TIMESTAMP   NULL,
   `PICKUP_COUNT`   INT(10)   NULL,
   `PICKUP_CENTERNAME`   VARCHAR(20)   NULL,
   `PICKUP_CNETERADDRESS`   VARCHAR(50)   NULL,
   `PICKUP_CARNUM`   VARCHAR(8)   NULL,
   `PICKUP_CARTYPE`   VARCHAR(8)   NULL,
   `PICKUP_CARNUMCOLOR`   VARCHAR(10)   NULL,
   `PICKUP_CAROUT`   VARCHAR(1)   NULL
);

CREATE TABLE `PAYMENT` (
   `PAYMENT_SEQUENCE`   Int   NOT NULL AUTO_INCREMENT PRIMARY KEY,
   `USER_SEQUENCE`   VARCHAR(20)  NULL,
   `PAYMENT_DATE`   TIMESTAMP   NULL,
   `PAYMENT_MARKING`   INT(3)   NULL,
   `PAYMENT_CHARGE`   INT(5)   NULL,
   `PAYMENT_DEPOSIT`   INT(8)   NULL
);


